## 端口号 上下文路径
server:
  port: 8080
  servlet:
    context-path: /crm

## 数据源配置
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
    username: root
    password: rootroot
  ## freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
  ## 启用热部署 devtools:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

## mybatis 配置 mybatis:
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.whq.crm.vo;com.whq.crm.query;com.whq.crm.dto
  configuration:
    map-underscore-to-camel-case: true

## pageHelper 分页
pagehelper:
  helper-dialect: mysql

## 设置 dao 日志打印级别
logging:
  level:
    com:
      whq:
        crm:
          dao: debug
